Other aircraft
fpw/avitab pull request #73
Opened 2020-09-02 18:31 UTC by mjh65

Hi Folke. Here are the updates to show other aircraft as overlays on the map. I've broken the updates into 3 separate commits. Regards, Michael.

2020-09-05 16:17 UTC, fpw requested changes
Thanks, looks great! And the thread boundary between X-Plane and AviTab is properly implemented and protected as well. 

I only had a few minor stylistic remarks. They're so minor that I would also accept this PR in its current state - just tell me if you want that.

2020-09-05 16:17 UTC, fpw commented on src/environment/standalone/StandAloneEnvironment.cpp
> +Location StandAloneEnvironment::getAircraftLocation(unsigned int id) {
This is cool, I like the idea of having moving AI aircraft in the standalone version for testing!

2020-09-05 16:17 UTC, fpw commented on src/environment/xplane/DataCache.cpp
> +    int id = plane * 4 + part;
I see that the aircraft id is sometimes a signed and sometimes an unsigned int, maybe just add a custom type for this? In C++11 that's as simple as adding `using AircraftID = unsigned int;` in some header.

2020-09-05 16:17 UTC, fpw commented on src/maps/OverlayedMap.cpp
> +    if (planeLocations.size() > 0) {
There's `vector::empty()` to check if a vector is empty, but that's just a minor thing.

2020-09-07 17:14 UTC, mjh65 commented
I've made a few more changes after your review, and after feedback from David and others during a test flight at the weekend.

2020-09-07 19:03 UTC, fpw requested changes
Thanks for the changes! The new additions introduced a few other minor things, but after that I'll merge it 🙂

2020-09-09 14:46 UTC, fpw approved these changes
Thanks for considering the suggestions!

2020-09-09 14:46 UTC, merged